name: AGAVE
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
  - r
dependencies:
  - biopython=1.79
  - ncurses=6.2
  - nodejs=14.11.0
  - numpy=1.21.4
  - openssl=1.1.1l
  - pandas=1.3.4
  - pip=21.3.1
  - python=3.9.7
  - pyvcf=0.6.8
  - readline=8.1
  - setuptools=58.5.3
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - wheel=0.37.0
  - zlib=1.2.11
