name: AGAVE
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
  - r
dependencies:
  - biopython=1.79
  - ca-certificates=2021.10.8
  - icu=67.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=12.0.1
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.18
  - libuv=1.39.0
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - ncurses=6.2
  - nodejs=14.11.0
  - numpy=1.21.4
  - openssl=1.1.1l
  - pandas=1.3.4
  - pip=21.3.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - pyvcf=0.6.8
  - readline=8.1
  - setuptools=58.5.3
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
